development:
  adapter: postgresql
  encoding: unicode
  database: good_questions_dev
  pool: 20
  username: root
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: good_questions_test
  pool: 20
  username: root
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: good_questions_prod
  pool: 256
  username: root
  password: password
