development:
  adapter: postgresql
  encoding: unicode
  database: fcm_development
  pool: 20
  username: root
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: fcm_test
  pool: 20
  username: root
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: fcm_production
  pool: 256
  username: root
  password: password
